export interface RouteStop {
  id: string;
  name: string;
  address: string;
  lat: number;
  lng: number;
  startTime: string;
  endTime: string;
}

export interface OptimizedRoute {
  stops: RouteStop[];
  totalDistance: number;
  estimatedTime: number;
  mapUrl: string;
}

export class RoutePlanner {
  /**
   * Optimizes a route for estate sales using a simple greedy algorithm
   * 
   * Cheapest implementation path:
   * 1. Use client-side calculation to avoid server costs
   * 2. Implement greedy nearest neighbor algorithm (not perfect but functional)
   * 3. Generate Google Maps URL for visualization
   * 4. Create printable plan with directions
   * 
   * For future enhancement, we could integrate with:
   * - OpenStreetMap (free but requires more setup)
   * - Google Routes API (paid but more accurate)
   * - Mapbox Optimization API (paid but good balance)
   */
  static async optimizeRoute(
    stops: RouteStop[], 
    startLocation: { lat: number; lng: number }
  ): Promise<OptimizedRoute> {
    // Simple greedy algorithm for route optimization
    const optimizedStops = [...stops];
    let currentPosition = startLocation;
    let totalDistance = 0;
    let totalTime = 0;
    
    // Sort stops by proximity to current position
    for (let i = 0; i < optimizedStops.length; i++) {
      let nearestIndex = i;
      let nearestDistance = Number.MAX_VALUE;
      
      // Find the nearest unvisited stop
      for (let j = i; j < optimizedStops.length; j++) {
        const distance = this.calculateDistance(
          currentPosition.lat,
          currentPosition.lng,
          optimizedStops[j].lat,
          optimizedStops[j].lng
        );
        
        if (distance < nearestDistance) {
          nearestDistance = distance;
          nearestIndex = j;
        }
      }
      
      // Swap the nearest stop to the current position
      [optimizedStops[i], optimizedStops[nearestIndex]] = 
        [optimizedStops[nearestIndex], optimizedStops[i]];
      
      // Update current position
      currentPosition = {
        lat: optimizedStops[i].lat,
        lng: optimizedStops[i].lng
      };
      
      // Add distance and time estimates
      totalDistance += nearestDistance;
      // Estimate 30 minutes per stop + travel time
      totalTime += 0.5 + (nearestDistance / 50); // Assuming 50 km/h average speed
    }
    
    // Generate Google Maps URL for the route
    const mapUrl = this.generateMapUrl(optimizedStops, startLocation);
    
    return {
      stops: optimizedStops,
      totalDistance: parseFloat(totalDistance.toFixed(2)),
      estimatedTime: parseFloat(totalTime.toFixed(2)),
      mapUrl
    };
  }
  
  /**
   * Calculates distance between two points using Haversine formula
   */
  private static calculateDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
    const R = 6371; // Radius of the earth in km
    const dLat = this.deg2rad(lat2 - lat1);
    const dLon = this.deg2rad(lon2 - lon1);
    const a =
      Math.sin(dLat / 2) * Math.sin(dLat / 2) +
      Math.cos(this.deg2rad(lat1)) *
        Math.cos(this.deg2rad(lat2)) *
        Math.sin(dLon / 2) *
        Math.sin(dLon / 2);
    const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
    const d = R * c; // Distance in km
    return d;
  }
  
  private static deg2rad(deg: number): number {
    return deg * (Math.PI / 180);
  }
  
  /**
   * Generates a Google Maps URL for the route
   */
  private static generateMapUrl(stops: RouteStop[], startLocation: { lat: number; lng: number }): string {
    // Start with the starting location
    let url = `https://www.google.com/maps/dir/?api=1&origin=${startLocation.lat},${startLocation.lng}`;
    
    // Add waypoints for each stop
    if (stops.length > 0) {
      const waypoints = stops.map(stop => `${stop.lat},${stop.lng}`).join('|');
      url += `&waypoints=${encodeURIComponent(waypoints)}`;
    }
    
    // End at the last stop
    if (stops.length > 0) {
      const lastStop = stops[stops.length - 1];
      url += `&destination=${lastStop.lat},${lastStop.lng}`;
    }
    
    url += '&travelmode=driving';
    return url;
  }
  
  /**
   * Generates a printable plan for the route
   */
  static generatePrintablePlan(route: OptimizedRoute): string {
    let plan = `# Estate Sales Route Plan\n\n`;
    plan += `**Total Distance:** ${route.totalDistance} km\n`;
    plan += `**Estimated Time:** ${route.estimatedTime.toFixed(1)} hours\n\n`;
    plan += `## Route Stops:\n\n`;
    
    route.stops.forEach((stop, index) => {
      plan += `${index + 1}. **${stop.name}**\n`;
      plan += `   Address: ${stop.address}\n`;
      plan += `   Hours: ${stop.startTime} - ${stop.endTime}\n`;
      plan += `   Coordinates: ${stop.lat}, ${stop.lng}\n\n`;
    });
    
    plan += `## Navigation:\n`;
    plan += `[View Route on Google Maps](${route.mapUrl})\n\n`;
    plan += `---\n*Generated by SaleScout*\n`;
    
    return plan;
  }
}
